baseURL = "https://thiagoprocaci.github.io"
title = "Thiago B. Procaci"
theme = "erblog"
[pagination]
  pagerSize = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
[services]
  [services.googleAnalytics]
    ID = "G-9FD4YJEVNQ"

[params]
    author = "Thiago Procaci"
    # logo = "//blog.ertuil.top/avater.png"
    
    bio = """
    <p> 
        Engineering Lead passionate about building high-impact systems at scale. I combine deep expertise in software engineering, data platforms, and machine learning to drive innovation and deliver results.
    </p>
    <br />
    <p>
        With a PhD in Computer Science specializing in machine learning and social network analysis, I bring both academic rigor and hands-on experience as a programmer, data engineer, and data scientist.
    </p>
    <br />
    <p>
        Today, I lead teams that design scalable architectures and ship cutting-edge features powered by LLMs.
    </p>
   
    """
    copyright = " "

    portrait = "https://avatars2.githubusercontent.com/u/721009?s=460&v=4"

    description = "Ways to reach me"

[[menu.main]]
    identifier = "about"
    name = "Skills and Publications"
    url = "/about/"
    weight = 10

# [[menu.main]]
#     identifier = "zone"
#     name = "Zone"
#     url = "/zone/"
#     weight = 10

#[[menu.footer]]
#    identifier = "home"
#    name = "home"
#    url = "/"
#    weight = 1

#[[menu.footer]]
#    identifier = "about"
#    name = "About"
#    url = "/about/"
#    weight = 2

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[[menu.icon]]
    url = "mailto:thiago.procaci@uniriotec.br"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/thiagoprocaci"
    name = "github"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/thiagoprocaci"
    name = "twitter"
    weight = 1

[[menu.icon]]
    url = "https://stackoverflow.com/users/5854925/thiago-procaci"
    name = "stack-overflow"
    weight = 1

[[menu.icon]]
    url = "https://www.linkedin.com/in/thiagoprocaci"
    name = "linkedin"
    weight = 1

[[menu.icon]]
    url = "https://medium.com/@tprocaci"
    name = "medium"
    weight = 1







